name: "Documenso Contributor License Agreement"
description: "Check if contributor has signed the CLA"
author: "Documenso"

runs:
  using: node20
  main: dist/index.js

branding:
  icon: "heart"
  color: "red"

inputs:
  github-token:
    description: "GitHub token"
    required: true
  cla-endpoint:
    description: "Endpoint to check CLA status"
    required: true
  cla-link:
    description: "Link to sign the CLA"
    required: true
