name: Documenso CLA

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CLA check
        uses: ./
        with:
          github-token: ${{ secrets.CLA_GITHUB_TOKEN }}
          cla-endpoint: ${{ secrets.CLA_ENDPOINT }}
          cla-link: ${{ secrets.CLA_LINK }}
